### ISSUE TITLE
unknown chip id! 0x10076415

### ISSUE THREAD

**Issue by kuobakuoba** [stm32duino/wiki#1]
I connected my STM32L476RG to the arduinoIDE with according settings.
<img width="367" alt="1191388541" src="https://user-images.githubusercontent.com/20016691/27118709-1de94858-510f-11e7-9865-0baf5d924af4.png">
And upload a Blink example from the IDE.

But I get these errors.
<img width="1026" alt="2017-06-14 2 39 14" src="https://user-images.githubusercontent.com/20016691/27118863-dab12474-510f-11e7-978d-f3d45749275a.png">
<img width="394" alt="2017-06-14 2 46 07" src="https://user-images.githubusercontent.com/20016691/27118948-4737988a-5110-11e7-929e-eed570628d21.png">

I am running mac with sierra.
![2017-06-14 2 41 12](https://user-images.githubusercontent.com/20016691/27119132-3188d3a4-5111-11e7-88d3-c424b3ceb376.png)
I have eclipse with Ac6 for STM32 and it works with no problem.
How can I get STM32duino to work?
Thanks.

**Comment by fpistm** [comment]
This issue was moved to stm32duino/Arduino_Core_STM32#31
