### ISSUE TITLE
Broken links to X-Nucleo-BNRG2A1 binary files.

### ISSUE THREAD

**Issue by Mark-G1** [stm32duino/wiki#2]
The links for the X-Nucleo-BNRG2A1 binary files, [DTM_LLOnly.bin](https://github.com/stm32duino/wiki/raw/master/X-NUCLEO-BNRG2A1/DTM_LLOnly.bin)
and  [DTM_Full.bin](https://github.com/stm32duino/wiki/raw/master/X-NUCLEO-BNRG2A1/DTM_Full.bin) 
result in a 404 error.

I was not able to find the X-Nucleo-BNRG2A1 repository when searching under the stm32duino space.

**Comment by Mark-G1** [comment]
In case it helps anyone: I was able to find binary files with the same names in the STM32Cube function pack [FP-IND-PREDMNT1 (version 2.4.0).](https://www.st.com/en/embedded-software/fp-ind-predmnt1.html#get-software)  

Extract the zip file and the 2 binary files are located in the path:

STM32CubeFunctionPack_PREDMNT1_V2.4.0/Utilities/BlueNRG-1_2_Flasher/

**Comment by cparata** [comment]
Hello @Mark-G1 ,
thanks for the notification. I fixed the links. Now they should be fine.
Best Regards,
Carlo
